#!/usr/bin/env python3
"""Generate crates/strata-engine/src/langs_table.rs from vendored linguist data.

Usage: python3 tools/gen_langs.py   (reads tools/vendor/{languages,vendor}.yml)
Re-download the inputs with:
  curl -sSfL -o tools/vendor/languages.yml https://raw.githubusercontent.com/github-linguist/linguist/main/lib/linguist/languages.yml
  curl -sSfL -o tools/vendor/vendor.yml https://raw.githubusercontent.com/github-linguist/linguist/main/lib/linguist/vendor.yml
"""

import pathlib

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
LANGS = yaml.safe_load((ROOT / "tools/vendor/languages.yml").read_text())
VENDOR = yaml.safe_load((ROOT / "tools/vendor/vendor.yml").read_text())
OUT = ROOT / "crates/strata-engine/src/langs_table.rs"

# When several languages claim one extension, the earliest name here wins.
POPULAR = [
    "C", "C++", "Rust", "Python", "JavaScript", "TypeScript", "TSX", "Go", "Java", "Kotlin",
    "C#", "Shell", "Markdown", "JSON", "YAML", "TOML", "HTML", "CSS", "SCSS", "Ruby", "PHP",
    "Perl", "Objective-C", "Swift", "Scala", "Haskell", "OCaml", "Lua", "SQL", "Makefile",
    "Dockerfile", "Assembly", "Unix Assembly", "Verilog", "SystemVerilog", "Text", "XML",
    "reStructuredText", "TeX", "Emacs Lisp", "Common Lisp", "Clojure", "Elixir", "Erlang",
    "Dart", "R", "Julia", "MATLAB", "Fortran", "Pascal", "Vue", "Svelte", "Nix", "HCL",
    "Protocol Buffer", "GraphQL", "Batchfile", "PowerShell", "Vim Script", "CMake",
    "Groovy", "Zig", "Jupyter Notebook", "CSV", "INI", "Diff", "Linker Script", "Roff",
    "Device Tree", "Awk", "Coccinelle", "Raku", "Prolog", "Smalltalk", "Racket", "F#",
]
RANK = {n: i for i, n in enumerate(POPULAR)}
TYPE_CODE = {"programming": 0, "markup": 1, "data": 2, "prose": 3}


def rank(name, lang, ext):
    primary = 0 if lang.get("extensions", [None])[0] == ext else 1
    return (RANK.get(name, 10_000), primary, TYPE_CODE.get(lang.get("type"), 9), name)


names = sorted(LANGS)
index = {n: i for i, n in enumerate(names)}
ext_candidates: dict[str, list[str]] = {}
file_candidates: dict[str, list[str]] = {}
for name, lang in LANGS.items():
    for ext in lang.get("extensions", []) or []:
        ext_candidates.setdefault(ext.lower(), []).append(name)
    for fn in lang.get("filenames", []) or []:
        file_candidates.setdefault(fn, []).append(name)

ext_map = {
    ext: min(c, key=lambda n: rank(n, LANGS[n], ext)) for ext, c in ext_candidates.items()
}
file_map = {
    fn: min(c, key=lambda n: rank(n, LANGS[n], None)) for fn, c in file_candidates.items()
}


def s(v):
    return '"' + v.replace("\\", "\\\\").replace('"', '\\"') + '"'


lines = [
    "// @generated by tools/gen_langs.py from github-linguist data (MIT). Do not edit.",
    "",
    "/// (name, type: 0 programming, 1 markup, 2 data, 3 prose)",
    "pub static LANGS: &[(&str, u8)] = &[",
]
for n in names:
    lines.append(f"    ({s(n)}, {TYPE_CODE.get(LANGS[n].get('type'), 3)}),")
lines += ["];", "", "/// Lowercased extension (with dot) -> index into LANGS, sorted for binary search.",
          "pub static EXTENSIONS: &[(&str, u16)] = &["]
for ext in sorted(ext_map):
    lines.append(f"    ({s(ext)}, {index[ext_map[ext]]}),")
lines += ["];", "", "/// Exact filename -> index into LANGS, sorted for binary search.",
          "pub static FILENAMES: &[(&str, u16)] = &["]
for fn in sorted(file_map):
    lines.append(f"    ({s(fn)}, {index[file_map[fn]]}),")
lines += ["];", "", "/// linguist vendor.yml regexes (Ruby syntax; entries Rust's regex rejects are skipped at load).",
          "pub static VENDOR_PATTERNS: &[&str] = &["]
for pat in VENDOR:
    lines.append(f"    {s(pat)},")
lines += ["];", ""]
OUT.write_text("\n".join(lines))
print(f"wrote {OUT.relative_to(ROOT)}: {len(names)} languages, {len(ext_map)} extensions, "
      f"{len(file_map)} filenames, {len(VENDOR)} vendor patterns")
